# -*- coffee -*- -p
author: YC <yinso.chen@gmail.com>
name: tinyweb
description: A small extensible web server
version: 0.2.0
repository:
  type: git
  url: git://github.com/yinso/tinyweb.git
main: ./lib/main
bin:
  tinyweb: ./bin/tinyweb
engines:
  node: '>= 0.8.4'
scripts:
  test: make test
  prepublish: make
dependencies:
  yargs: =1.3.2
  js-yaml: =3.2.2
  express: =4.11.2
  coffee-script: =1.8.0
  pretty-data: =0.40.0
  loglet: '>=0.1.0'
  coffee-bean: '>=0.3.0'
  underscore: '=1.7.0'
  filelet: '>=0.1.2'
  loglet: '>=0.1.2'
  # express middleware that have been separated out.
  'cookie-parser': '=1.3.2'
  'serve-favicon': '=2.0.1'
  'body-parser': '=1.6.3'
  'method-override': '=2.1.3'
  'express-session': '=1.7.5'
  node-uuid: =1.4.2
  cookie: =0.1.2
  watch: =0.16.0
  marked: =0.3.3
  handlebars: =3.0.2
  lru-cache: =2.6.1
devDependencies:
  testlet: '>= 0.2.0'
