// Generated by CoffeeScript 1.4.0
(function() {
  var extless, fs, loglet, path;

  fs = require('fs');

  path = require('path');

  loglet = require('loglet');

  extless = function(options) {
    return function(req, res, next) {
      if (!(req.url === '/') && !req.url.match(/\..+$/)) {
        req.url += '.html';
      }
      loglet.debug('server.extless', req.url, !(req.url === '/'), !req.url.match(/^\..+$/));
      return next();
    };
  };

  module.exports = extless;

}).call(this);
